export const ICON: {
  file: Record<string, string>,
  folder: Record<string, string>,
} = {
  file: {
    'js': 'javascript',
    'ts': 'typescript',
    'jsx': 'react',
    'tsx': 'react_ts',
    'json': 'json',
    'jsonc': 'json',
    'json5': 'json',
    'html': 'html',
    'txt': 'document',
    'vue': 'vue',
    'gitignore': 'git',
    'md': 'markdown',
    'license': 'certificate',
    'zip': 'zip',
    'tar': 'zip',
    'mp3': 'audio',
    'mp4': 'video',
    'mov': 'video',

    'css': 'css',
    'less': 'less',
    'sass': 'sass',
    'scss': 'sass',
    'styl': 'stylus',

    'png': 'image',
    'jpeg': 'image',
    'jpg': 'image',
    'gif': 'image',
    'ico': 'image',
    'svg': 'svg',
  },
  folder: {
    '.git': 'git',
    '.gitlab': 'folder-gitlab',
    '.vscode': 'folder-vscode',
    'dist': 'folder-dist',
    'log': 'folder-log',
    'logs': 'folder-log',
    'node_modules': 'folder-node',
    'public': 'folder-public',
    'src': 'folder-src',
    'components': 'folder-components',
    'assets': 'folder-resource',
    'hooks': 'folder-hook',
    'styles': 'folder-styles',
    'utils': 'folder-utils',
    'view': 'folder-view',
    'views': 'folder-view',
    'page': 'folder-page',
    'pages': 'folder-page',
    'config': 'folder-config',
    'configs': 'folder-config',
    'home': 'folder-home',
    'typescript': 'folder-typescript',
    'ts': 'folder-typescript',
    'typings': 'folder-typescript',
    '@types': 'folder-typescript',
    'types': 'folder-typescript',
    'vue': 'folder-vue',
    'debug': 'folder-debug',
    'icon': 'folder-icon',
    'icons': 'folder-icon',
  },
}
